"""
Django settings for cursapp_bcken project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-thok(*w@#w9eb%4y#ic7lo(og55pta_clxurn+6ha194zu#i($'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core.apps.CoreConfig',
    'cursos.apps.CursosConfig',
    'evaluacion.apps.EvaluacionConfig',
    'api.apps.ApiConfig',
    'recomendacion.apps.RecomendacionConfig',
    'comunidad.apps.ComunidadConfig',
    'django_celery_results',
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'tasa-bcv-cache',
    }
}

# -------------------------------------------------------------
# Configuración de Django REST Framework (DRF)
# -------------------------------------------------------------
REST_FRAMEWORK = {
    # JSONRenderer y JSONParser por defecto (estándar REST)
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser' # Necesario para subir archivos (como SCORM/videos)
    ],
    
    # Autenticación: Prioriza JWT.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    
    # Permisos: Solo usuarios autenticados por defecto
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # Paginación 
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20 # 20 items por página en listas
}

# -------------------------------------------------------------
# Configuración de Simple JWT (JSON Web Tokens)
# -------------------------------------------------------------
from datetime import timedelta

SIMPLE_JWT = {
    # Configuración de la caducidad del token
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # Token de acceso expira en 60 minutos
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), # Token de refresco dura 7 días
    
    # Ajustes de seguridad
    'ROTATE_REFRESH_TOKENS': True, # Mejora la seguridad forzando nuevos tokens de refresco
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, # Usa la clave secreta de Django para firmar
    'AUTH_HEADER_TYPES': ('Bearer',), # Estándar para APIs
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': (
        'rest_framework_simplejwt.tokens.AccessToken',
    ),
    'TOKEN_TYPE_CLAIM': 'token_type',
}


# -------------------------------------------------------------
# Configuración del Modelo de Usuario Personalizado (para Roles)
# -------------------------------------------------------------
AUTH_USER_MODEL = 'core.Usuario'

# Configuración de Archivos de Medios (para contenido multimedia)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cursapp_bcken.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cursapp_bcken.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------------
# Configuración de Tareas Asíncronas (CELERY)
# -------------------------------------------------------------
# Broker (Redis) - Dónde se encolan las tareas
CELERY_BROKER_URL = 'redis://localhost:6379/0' 

# Backend (Redis o DB) - Dónde se guardan los resultados de las tareas
CELERY_RESULT_BACKEND = 'django-db' # Usamos la BD de Django (via django_celery_results)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE