# Generated by Django 5.2.7 on 2025-10-30 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('imagen_url', models.URLField(max_length=500)),
                ('criterio_logros', models.CharField(help_text='Criterio a cumplir para obtener la insignia.', max_length=255)),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
            },
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('calificacion_minima', models.DecimalField(decimal_places=2, default=70.0, help_text='Porcentaje mínimo requerido para aprobar.', max_digits=6)),
                ('maximo_intentos', models.PositiveSmallIntegerField(default=3, help_text='Número máximo de veces que el alumno puede intentar el cuestionario.')),
                ('leccion', models.OneToOneField(help_text='Cuestionario asociado a esta lección.', on_delete=django.db.models.deletion.CASCADE, related_name='cuestionario', to='cursos.leccion')),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('porcentaje_progreso', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de finalización total del curso.', max_digits=5)),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación promedio al final del curso.', max_digits=5, null=True)),
                ('alumno', models.ForeignKey(limit_choices_to={'rol': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_curso', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('alumno', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código único e inmutable para la verificación del certificado.', unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('url_certificado', models.URLField(blank=True, help_text='URL al documento PDF/imagen del certificado.', max_length=500, null=True)),
                ('inscripcion', models.OneToOneField(help_text='Inscripción que generó este certificado.', on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='evaluacion.inscripcion')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
        migrations.CreateModel(
            name='IntentoCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('puntuacion_obtenida', models.DecimalField(decimal_places=2, max_digits=5)),
                ('puntuacion_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aprobado', models.BooleanField(default=False)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.cuestionario')),
                ('inscripciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_cuestionario', to='evaluacion.inscripcion')),
            ],
            options={
                'verbose_name': 'Intento de Cuestionario',
                'verbose_name_plural': 'Intentos de Cuestionario',
                'ordering': ['-fecha_intento'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField()),
                ('tipo_pregunta', models.PositiveSmallIntegerField(choices=[(1, 'Opción Múltiple'), (2, 'Verdadero/Falso'), (3, 'Emparejamiento')], default=1)),
                ('puntuacion', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('cuestionario', models.ManyToManyField(blank=True, help_text='Los cuestionarios que usan esta pregunta.', related_name='preguntas', to='evaluacion.cuestionario')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='evaluacion.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
            },
        ),
        migrations.CreateModel(
            name='InsigniaObtenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(limit_choices_to={'rol': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='insignias_obtenias', to=settings.AUTH_USER_MODEL)),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.insignia')),
            ],
            options={
                'verbose_name': 'Insignia Obtenida',
                'verbose_name_plural': 'Insignias Obtenidas',
                'unique_together': {('alumno', 'insignia')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_dedicado_minutos', models.PositiveIntegerField(default=0, help_text='Tiempo total que el alumno ha pasado en la lección.')),
                ('porcentaje_visto', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de video/contenido visto.', max_digits=5)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_lecciones', to='evaluacion.inscripcion')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.leccion')),
            ],
            options={
                'verbose_name': 'Progreso de Lección',
                'verbose_name_plural': 'Progresos de Lección',
                'unique_together': {('inscripcion', 'leccion')},
            },
        ),
    ]
