# Generated by Django 5.2.7 on 2025-10-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estado_pago',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pendiente de Pago'), (2, 'Pagado'), (3, 'Fallido/Cancelado')], default=1, verbose_name='Estado de Pago'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='precio_pagado_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio en USD del curso al momento de la inscripción.', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
