# Generated by Django 5.2.7 on 2025-10-31 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_alter_inscripcion_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descipcion', models.TextField()),
                ('costo_puntos', models.PositiveIntegerField(help_text='Costo de la recompensa en puntos.')),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
            },
        ),
        migrations.CreateModel(
            name='PuntosAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0, help_text='Puntos ganados o restados')),
                ('motivo', models.CharField(help_text='Razón por la cual se otorgaron/restaron los puntos.', max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(limit_choices_to={'rol': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='puntos_ganados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puntos de Alumno',
                'verbose_name_plural': 'Puntos de Alumnos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='CanjeRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(limit_choices_to={'rol': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='canjes_realizados', to=settings.AUTH_USER_MODEL)),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.recompensa')),
            ],
            options={
                'verbose_name': 'Canje de Recompensa',
                'verbose_name_plural': 'Canjes de Recompensa',
                'ordering': ['-fecha_canje'],
            },
        ),
    ]
