# Generated by Django 5.2.7 on 2025-10-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_recompensa_puntosalumno_canjerecompensa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresoleccion',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
