# Generated by Django 5.2.7 on 2025-11-01 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_etiqueta_alter_categoria_options_and_more'),
        ('evaluacion', '0004_alter_progresoleccion_fecha_completado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteraccionLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_interes', models.PositiveSmallIntegerField(default=0, help_text='Tasa de interés implícita')),
                ('ultima_vista', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to=settings.AUTH_USER_MODEL)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='cursos.leccion')),
            ],
            options={
                'verbose_name': 'Interacción de Lección',
                'verbose_name_plural': 'Interacciones de Lección',
                'unique_together': {('alumno', 'leccion')},
            },
        ),
    ]
