# Generated by Django 5.2.7 on 2025-11-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0005_interaccionleccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recompensa',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
