# Generated by Django 5.2.7 on 2025-11-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0006_rename_descipcion_recompensa_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresoleccion',
            name='entry_point',
            field=models.CharField(blank=True, default='ab-initio', max_length=10),
        ),
        migrations.AddField(
            model_name='progresoleccion',
            name='estado_scorm',
            field=models.CharField(blank=True, choices=[('passed', 'Aprobado'), ('completed', 'Completado'), ('failed', 'Fallido'), ('incomplete', 'Incompleto'), ('browsed', 'Visto por encima'), ('not attempted', 'No intenrado')], default='Not attempted', max_length=20),
        ),
        migrations.AddField(
            model_name='progresoleccion',
            name='puntuacion_scorm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puntuación (0-100) reportada por el SCORM', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='progresoleccion',
            name='suspend_data',
            field=models.TextField(blank=True, help_text='Datos de suspensión del SCORM (dónde guardar)', null=True),
        ),
    ]
