# Generated by Django 5.2.7 on 2025-11-02 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0008_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comision_plataforma_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_instructor_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comision_aplicada_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado_pago_instructor', models.CharField(choices=[('pendiente', 'Pendiente de Pago al Instructor'), ('pagado', 'Pagado al Instructor'), ('reembolsado', 'Reembolsado al Alumno')], db_index=True, default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago_instructor', models.DateTimeField(blank=True, null=True)),
                ('inscripcion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion', to='evaluacion.inscripcion')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
