# Generated by Django 5.2.7 on 2025-11-05 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_curso_portada'),
        ('evaluacion', '0009_transaccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresoleccion',
            name='estado_scorm',
            field=models.CharField(blank=True, choices=[('passed', 'Aprobado'), ('completed', 'Completado'), ('failed', 'Fallido'), ('incomplete', 'Incompleto'), ('browsed', 'Visto por encima'), ('not attempted', 'No intenrado')], default='not attempted', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('alumno', 'curso')},
        ),
    ]
