# Generated by Django 5.2.7 on 2025-10-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='entidad_verificada',
            field=models.CharField(blank=True, help_text='Nombre de la Universidad/Organización si aplica.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Indica si la cuenta ha sido verificada oficialmente por la plataforma.'),
        ),
    ]
