# Generated by Django 5.2.7 on 2025-11-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_entidad_verificada_usuario_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='puntos_totales',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Moneda virtual para canjear por recompensas.'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='xp_totales',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Puntos de experiencia para subir de nivel.'),
        ),
    ]
