# Generated by Django 5.2.7 on 2025-10-30 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL amigable', max_length=255, unique=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('precio_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio USD', max_digits=8)),
                ('req_certificado', models.BooleanField(default=False)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Borrador'), (2, 'Publicado'), (3, 'Suspendido')], default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'rol': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=500)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el curso.')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['orden'],
                'unique_together': {('curso', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tipo_contenido', models.PositiveSmallIntegerField(choices=[(1, 'Video'), (2, 'Documento/PDF'), (3, 'Cuestionario/Examen'), (4, 'Paquete SCORM')], default=1, verbose_name='Tipo de Contenido')),
                ('archivo_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ruta o URL del contenido multimedia/SCORM')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='lecciones/%Y/%m/')),
                ('duracion_minutos', models.PositiveIntegerField(default=0, help_text='Tiempo estimado de duración.')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='cursos.modulo')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['orden'],
                'unique_together': {('modulo', 'orden')},
            },
        ),
    ]
