# Generated by Django 5.2.7 on 2025-11-01 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Clasificación principal del curso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='cursos.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, help_text='Palabras claves para búsqueda y recomendación.', related_name='cursos', to='cursos.etiqueta'),
        ),
    ]
