# Generated by Django 5.2.7 on 2025-11-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_etiqueta_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='promedio_calidad_contenido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='curso',
            name='promedio_calificacion_general',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='curso',
            name='promedio_claridad_explicacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='curso',
            name='promedio_soporte_instructor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='curso',
            name='promedio_utilidad_practica',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='curso',
            name='total_resenas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
