# Generated by Django 5.2.7 on 2025-11-02 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_promedio_calidad_contenido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='El código que el alumno usará', max_length=50, unique=True)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, help_text='Descuento en porcentaje (ej. 25.00)', max_digits=5)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('usos_maximos', models.PositiveIntegerField(default=100)),
                ('usos_actuales', models.PositiveIntegerField(default=0, editable=False)),
                ('cursos', models.ManyToManyField(blank=True, help_text='Cursos a los que aplica ete cupón.', related_name='cupones', to='cursos.curso')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'rol': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
    ]
