# Generated by Django 5.2.7 on 2025-11-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='estado_procesamiento',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando Video'), ('completado', 'Completado y Listo'), ('error', 'Error de Procesamiento')], default='pendiente', max_length=20),
        ),
    ]
