# Generated by Django 5.2.7 on 2025-11-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_leccion_tipo_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='tipo_contenido',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Video'), (2, 'Documento/PDF'), (3, 'Cuestionario/Examen'), (4, 'Paquete SCORM'), (5, 'Artículo')], default=1, verbose_name='Tipo de Contenido'),
        ),
    ]
