# Generated by Django 5.2.7 on 2025-11-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_alter_leccion_tipo_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='cuerpo_articulo',
            field=models.TextField(blank=True, help_text='Contenido en Markdown para lecciones de tipo Artículo/Código.', null=True),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='tipo_contenido',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Video'), (2, 'Documento/PDF'), (3, 'Cuestionario/Examen'), (4, 'Paquete SCORM'), (5, 'Artículo/Código')], default=1, verbose_name='Tipo de Contenido'),
        ),
    ]
