# Generated by Django 5.2.7 on 2025-11-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_leccion_cuerpo_articulo_alter_leccion_tipo_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='portada',
            field=models.ImageField(blank=True, default='https://plus.unsplash.com/premium_photo-1681426414801-f36575c2de9e?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y292ZXJ8ZW58MHx8MHx8fDA%3D&fm=jpg&q=60&w=3000', null=True, upload_to='portadas_curso/%Y/%m/', verbose_name='Imagen de Portada'),
        ),
    ]
